### ISSUE TITLE
[maintainers RFC] replace lgtm.co integration with requiring reviews

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/discussion#101]
GitHub [introduced their](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features) their new [pull request review feature](https://help.github.com/articles/reviewing-changes-in-pull-requests/) recently.

While I like the idea to enforce a review of two members of Hoodie’s Maintainers team, it didn’t work out very well. We bypassed the required two LGTMs often as administrators, for reasons like

- the PRs were very simple like [this one](https://github.com/hoodiehq/hoodie-account/pull/74) or all the Greenkeeper pull requests
- keeping noise down for maintainers, so they don’t ignore notifications when pinged, and only ping them for bigger pull requests. I’d rather trust our reviewers to make the right choice than enforcing 2 reviews for every pull request
- I’d like people sending pull requests not to wait for too long for their contribution to land

The "downside" for the review feature is that everyone can make a review (but only people with write access can merge). But it can be required for all pull requests, and authors cannot review their own pull requests.

From my experience doing many PR reviews in the past months, lgtm.co didn’t work out very well and I’d like to give GitHub’s own review feature a trial.

Thoughts? @hoodiehq/maintainers

**Comment by Charlotteis** [comment]
I agree with this move. As always, if it doesn't work, we can go to the previous process.
I prefer to use GitHubs internal tool and not rely on a third party which, though awesome, has gone done a couple times when I have tried to LGTM something.

**Comment by HipsterBrown** [comment]
After using the pull request review feature, I really enjoy being able to bundle a review into one notification and stream of consciousness. It reduces noise around a PR and allows for quicker feedback acceptance with that ability to merge suggested changes into the PR. 

Switching from lgtm.co to this new feature sounds like a positive experiment. :+1:

**Comment by rogeriochaves** [comment]
LGTM :P

**Comment by machikoyasuda** [comment]
I echo what @Charlotteis @HipsterBrown said. I like the idea of using GitHub's internal tool rather than a 3rd party tool because (selfishly) other organizations I am a part of are starting to use it too, and I want to practice it as well!

**Comment by gr2m** [comment]
Thanks everyone, I’ll take care of it :)
