### ISSUE TITLE
Store: Hoodie properties added to documents

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/discussion#105]
## Motivation

The current implementation of `hoodie.store` adds properties to the root of each document:

- _rev
- type
- createdAt
- updatedAt
- removedAt
- createdBy
- updatedBy
- removedBy

The idea was that these properties are most likely used by the app anyway. But the problems are 

- Hoodie’s properties are indistinguishable from an app’s custom properties 
- `type` is used for scoped stores (like `hoodie.store('note')`). This lead to a lot of confusion, complex implementation and the problem that app’s want to set `type` to custom values, e.g. a note can be a text note, an audio note or an image.
- It's hard to explain what these properties are, why they are special, and why they are ready-only

## Suggestion

All "Hoodie properties" are stored in the `.hoodie` property. This makes it easy for communication what Hoodie properties are and that they are all read-only while all other properties can be manipulated by the app (besides `id`).

So instead of 

```js
{
  "id": "u148pag",
  "_rev": "3-bg42z8cd5",
  "text": "Happy holidays!",
  "type": "note",
  "createdBy": "lgbquxv",
  "updatedBy": "lgbquxv",
  "updatedAt": "2016-12-20T19:28:49.560Z",
  "createdAt": "2016-12-20T19:27:02.344Z"
}
```

We would now have 

```js
{
  "id": "u148pag",
  "text": "Happy holidays!",
  "hoodie": {
    "revision": "3-bg42z8cd5",
    "type": "note",
    "createdBy": "lgbquxv",
    "updatedBy": "lgbquxv",
    "updatedAt": "2016-12-20T19:28:49.560Z",
    "createdAt": "2016-12-20T19:27:02.344Z"
  }
}
```

### Additional suggestions

- don’t add `.hoodie.updatedAt` timestamp on creation. That makes it possible to distinguish between revisions that created a document and the ones that updated it, as relying on the `_rev` property alone is not always accurate.

**Comment by sdvg** [comment]
I agree that these properties are confusing in the root of document objects 👍 Especially `type`.

But I'm not 100% happy with the idea of using something like `{{ note.hoodie.createdAt | date }}` in my views.
What do you think about putting only Hoodie internals (not meant to be rendered in most cases) like ID, revision and type in a `hoodie` object?

**Comment by gr2m** [comment]
can you explain why you would not be comfortable with `{{ note.hoodie.createdAt | date }}`? It would clearly show that this is a "Hoodie property", and all Hoodie APIs will guarantee for `note.hoodie` to exist. 

I will open a separate issue on `.type` soon, the current solution with it and the `hoodie.store(type)` API is not working well and is both confusing to people and buggy. More on that soon.

I thought keeping `id` in the root makes sense because the `.id` property is just such a omnipresent concept for interacting with any kind of database, moving it to the `hoodie.` property might cause problems later. I think just from a documentation perspective, explaining "Hoodie properties" and the "id" are okay to keep separated.

**Comment by gr2m** [comment]
@sdvg see https://github.com/hoodiehq/discussion/issues/106 for my thoughts on the `.type` property and the `hoodie.store(scope)` API

**Comment by sdvg** [comment]
I would prefer if my views would not need to know about hoodie as a storage. But this is not something I feel entirely uncomfortable with, more a small suggestion. 

If we remove the type property I would suggest to either keep all properties in the root or move all properties to 'hoodie' (id might be an exception). I tend to the first variant because 'type' was my biggest motivation to move and the reason I wrote about above.

**Comment by gr2m** [comment]
To add to the discussion, I’m curtain that plugins will want to add custom, internal properties in future, too. For example a migration plugin could add the last migration number to each document. These properties would need to go to a `.hoodie` namespace to make sure they do not conflict with properties used by app developers.

**Comment by pmbanugo** [comment]
Is `createdBy` & `updatedBy` the identifier as to who owns the document? Aside that and the type property,  I think it feels more comfortable to know that there is an `id` and timestamp (created and updated time) added as properties to items I save automatically. 

The `createdBy` & `updatedBy`  can be inside a .hoodie namespace, and also the `_rev` property (which I don't know it's use). 

Summary:
id, createdDate, and updatedDate should be in the root, while updatedBy, createdBy, removedBy can be placed within hoodie property.

**Comment by gr2m** [comment]
`createdBy`, `updatedBy` and `removedBy` will hold the id of the user account that created the document, updated it or removed it. The respective `*At` properties have the timestamps for it.

Why would you put some properties in the `.hoodie` namespace, while leaving the *By properties in the document root? You will still be able to access the timestamps with `myDoc.hoodie.createdAt` if you want to, but it will be clear that this properties was add by Hoodie and that you cannot alter its value

**Comment by pmbanugo** [comment]
Because for most applications I would want to expect the timestamp at the root of the object, just like I would the `_id` even though they're generated automatically, and will mostly not need the *By properties (i.e consuming the client API. I'm sure the *By properties are very much needed behind the server by hoodie). 

Another thought, we can have all hoodie generated properties within `.hoodie` including the `id`.

**Comment by janl** [comment]
In earlier versions of Hoodie we used `$` as a prefix for Hoodie-specific properties, so `createdAt` was `$createdAt`. While not very obvious, it does the job. I don’t remember why we stopped doing this. Gregor, can you fill me in?

That said, I think a dedicated sub-object as proposed here works too. Maybe we can prefix that with `$`, so user-data can have a top level “hoodie” field.

I wouldn’t split Hoodie-specific properties into more- and less-important as @pmbanugo suggests (sorry ;) — It’ll be an indefinite discussion on which are “important” and which are not, and people have to continuously look up (or trial-and-error) which Hoodie property lives where.

FWIW, differentiating user-data and meta-data is a long-running in the CouchDB developer community, let’s not spend too much time on this and move on, once we agree on a basic shape :)

Maybe in terms of spelling out the guidelines we can get somewhere:

Old Hoodie:

1. All top-level property names starting with an underscore `_` belong to CouchDB/PouchDB
2. All top-level property names starting with a dollar sign `$` belong to Hoodie and plugins
3. All other top-level property names can be freely chosen by the user.

This issue’s suggestion only changes rule 2.:

1. All top-level property names starting with an underscore `_` belong to CouchDB/PouchDB
2. A top level property name called `hoodie` belongs to Hoodie and plugins
3. All other top-level property names can be freely chosen by the user.

`$`-prefix is a little less obvious, but once learned it is easy and consistent.

In code, either looks fine to me:

```javascript
var thing_created = some_object.$createdAt;
```

```javascript
var thing_created = some_object.hoodie.createdAt;
```

or even both

```javascript
var thing_created = some_object.$hoodie.createdAt;
```

* * *

One question about `id`: Isn’t this `_id` as per CouchDB, or are we maintaining `id` and `_id`?

* * *

> don’t add .hoodie.updatedAt timestamp on creation. That makes it possible to distinguish between revisions that created a document and the ones that updated it, as relying on the _rev property alone is not always accurate.

This is good!

**Comment by gr2m** [comment]
We can hide away CouchDB / PouchDB internals entirely. We currently map CouchDB’s `_id` to Hoodie’s `id` property and we keep the `_rev` as is.

What I would suggest to do now is that we only have two special properties

1. `.id` is special as it is used to find documents and it can also be set to a custom value when creating the document
2. `.hoodie` is a special property which holds all the meta properites that Hoodie adds, and all of the are read-only. It will include `.hoodie.revision` which will be the same as CouchDB's `_rev` property.

I would in general through an error if someone tries to set a property starting with a `_` and ignore everything that is set in the `.hoodie` property. 

I wouldn’t like to call that property `.$hoodie` and allow users to set a custom value for `.hoodie`, I fear that would be rather confusing.

Plugins will be able to set their own `.hoodie` properties via hooks. 

I think with that we really only need to explain the "Hoodie properties". The `.id` property should be clear for most as it is a very common convention. And I would vote against putting the `.id` property into `.hoodie.id` because of that convention, and also because it can be set on creation, unlike the other `.hoodie` proeperties.

**Comment by janl** [comment]
>  wouldn’t like to call that property .$hoodie and allow users to set a custom value for .hoodie, I fear that would be rather confusing.

Where does the "custom value for .hoodie" come from? I agree we shouldn't do that.

And what are your objections for the $-prefix?

**Comment by gr2m** [comment]
> Where does the "custom value for .hoodie" come from? I agree we shouldn't do that.

```js
hoodie.store.add({foo: 'bar', hoodie: {custom: 'value'})
```

The passed `hoodie` property will be simply ignored.

> And what are your objections for the $-prefix?

Esthetics and clarity. If we had `.$hoodie` we would need to explain what the `$` means, not everyone knows that it’s a valid character for a JavaScript object property. And as mentioned above, if we used the `.$hoodie` property but would then allow a `.hoodie` property to be set by the user, that’s very confusing to me. It’s the same reason why we renamed `$createdAt` to `createdAt`.

**Comment by janl** [comment]
> The passed hoodie property will be simply ignored.

or throw a warning?

Same could go for the $-prefix. `console.warn('you added a property “createdAt”, did you mean `$createdAt`' )`

We could do the same for top-level properties that we already track inside `.hoodie`:

`store.add({createdAt: 123})` could `console.warn('you added a property “createdAt”. Hoodie is already tracking this for you in obj.hoodie.createdAt' )`.

> not everyone knows that it’s a valid character for a JavaScript object property

I’d say jQuery solved that for us :)

**Comment by gr2m** [comment]
> or throw a warning?

with hoodie you often have a document loaded, change some properties and then pass it back to `hoodie.store.update(doc)`. The `.hoodie` property will be present and I would not throw a warning because this is a very common usage pattern.

> Same could go for the $-prefix

We don’t know all these properties. We have some that from Hoodie core, but plugins will be able to add their own. For example `.hoodie.migration` or `.hoodie.sharedWith`

**Comment by janl** [comment]
> with hoodie you often have a document loaded, change some properties and then pass it back to hoodie.store.update(doc). The .hoodie property will be present and I would not throw a warning because this is a very common usage pattern.

yeah good point, if the `hoodie` property existed we can (and should) still validate it before we write it back, and throw a warning, or even error if that validation fails. At least then we catch uses of `obj.hoodie = 'foo'`.

My larger point here, and sorry for jumping into an implementation detail here,  was this: “The passed hoodie property will be simply ignored”. I wanted to see if we can make this as least surprising as possible that we are ignoring the setting of a property being ignored.

**Comment by janl** [comment]
> We can hide away CouchDB / PouchDB internals entirely. We currently map CouchDB’s _id to Hoodie’s id property and we keep the _rev as is.

> What I would suggest to do now is that we only have two special properties

> 1..id is special as it is used to find documents and it can also be set to a custom value when creating the document
> 2. .hoodie is a special property which holds all the meta properites that Hoodie adds, and all of the are read-only. It will include .hoodie.revision which will be the same as CouchDB's _rev property.

What I’m wondering is why we are trying to solve something that CouchDB has already solved (how to signify that id and rev are special. I understand that we need one more special field (or a prefix to for more special top-level fields) for just Hoodie things, but we seem to have moved a way from thinking of Hoodie as thin wrapper around P/CouchDB and more of a universe of its own.

Our previous thinking lead to using `_id`, `_rev` as-is and use `$createdAt` etc. in the top level for Hoodie-only things. Which I found a rather neat way of doing things. I understand that the $ might not be pretty, but, again citing jQuery, I think we’ve all gotten used to it, and it is not too confusing. From a complexity point of view, it’s the same (as demonstrated with the “rules” in a previous comment).

Especially owning a top level `id` field might be problematic when importing existing data. `hoodie` has less opportunity for a clash of course, but it’s still not immediately obvious from the property name that it *is* special. — Users can always write import/export tools for Hoodie that map their `id`, but it’s of course always easier if they don’t have to.

That said, maybe we want to do a top level `hoodie_id` and call the “property that holds all the other properties like `createdAt` `hoodie_metadata`. The established rule then is this:

Top level properties starting with `hoodie_` are reserved for Hoodie, everything else is free.

And then we can bikeshed whether we want `obj.hoodie_metadata.created_at` or `obj.hoodie_createdAt`. And of course whatever we use for `metadata` we can change too.

**Comment by gr2m** [comment]
@janl and I had some more discussion on this while we’ve been at the CouchDB Dev Summit in Boston 2 weeks ago.

Our recommendation is this:

- We don’t hide away any PouchDB properties any more, including the `_id` property. A PouchDB document is a valid Hoodie document, no more transforms.
- All hoodie properties will live in a `.hoodie` object, as suggested above.

That we we only need to explain to things to users regarding doc properties:

1. All properties prefixed with a `_` are  internal CouchDB/PouchDB properties and we will explain their meaning in our docs. 
2. The only property that hoodie adds is `.hoodie`. All `.hoodie.*` properties are read-only

With that change we will be able to remove a lot of transformation logic in our code and at the same time will make it easier for developers to switch between PouchDB/CouchDB & Hoodie

**Comment by janl** [comment]
Just to clarify, the JSON will look like this:

```json
{
    "_id": "abc",
    "_rev": "def",
    "hoodie": {
        "createdAt": "<timestamp>",
        "createdBy": "<userId>",
        "etc": "..."
    }
}
```

**Comment by gr2m** [comment]
on its way via https://github.com/hoodiehq/pouchdb-hoodie-api/issues/126
