### ISSUE TITLE
Move configuration from ./package.json to ./hoodie/config.js

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/discussion#107]
The current Hoodie Server is reading out default configuration like the `port` number or the path to your app’s public folder from the `"hoodie"` key in your app’s `"package.json"` file. We try to embrace the `npm` ecosystem and best practises as much as possible, and using the `"package.json"` file for your module’s configuration is is recommended by the npm team.

The problem is that the `package.json` file is JSON only and hence does not allow more complex configuration, like differentiation between development / test / production environments or accepting functions as configuration values. Because of that limitation, we currently cannot configure [custom account request handlers](https://github.com/hoodiehq/hoodie-account-server/tree/master/plugin#optionsrequests), among others.

I would therefore recommend that we deprecate the usage of the `package.json` for configuration and use a `hoodie/config.js` file instead. The `hoodie/` folder is the result of the discussion we had in https://github.com/hoodiehq/discussion/issues/98 and https://github.com/hoodiehq/hoodie/pull/637. 

The nice thing about having the `hoodie/` folder all to ourselves is that we could create it as part of setting up a hoodie app (we already use a post-install npm hook) and create the folder, the config.js file with default values and lots of comments as well as a README.md that can explain all things Hoodie-related. 

This is a fairly simple change and does not require breaking changes, we can phase out the configuration in `package.json` files gracefully via deprecation notices and eventual removal in future

### Use cases / Benefits

- JS files allow for comments, JSON does not. We could always generate the `hoodie/config.js` file with all default values set and extensive comments
- JS allows for more types, like regular expressions and functions
- A scripted configuration allows for different configuration based on `NODE_ENV`. 
- A scripted configuration allows to map existing ENV variables to the ones that Hoodie is looking for. For example, IBM’s bluemix automatically creates a `VCAP_SERVICES` environment variable which contains service credentials. Buried in there is is `.cloudantNoSQLDB[0].credentials.url` which contains the URL to the Cloudant Database, so we need to map it to the `dbUrl`. With a scripted configuration, that is as simple as `config.dbUrl = JSON.parse(process.env.VCAP_SERVICES).cloudantNoSQLDB[0].credentials.url`. Many deployment targets have an enviroment variable for a port, e.g. Bluemix has `VCAP_APP_PORT`

### Concerns

- **[JSON format allows for scripted manipulation of settings](https://github.com/hoodiehq/discussion/issues/107#issuecomment-269563318)**

  - The `.hoodierc` file remains and can be both in JSON and INI format. `hoodie/config.js` would be for configuration that is the same across environments only

**Comment by inator** [comment]
@gr2m: I'm indifferent to where the config resides, but feel the json format is useful and should be retained.  It allows for scripted manipulation of settings, which is important to us.  My suggestion is a hybrid approach, where the main config contains json attributes, and support be added for supplemental .js files where required.

**Comment by janl** [comment]
Not objecting to anything, just trying to clarify a few things:

> Because of that limitation, we currently cannot configure custom account request handlers, among others.

Wouldn't these rather live in plugins of some sort? I’m weary about application code in configuration.

>  like differentiation between development / test / production environments

Why would JSON not allow something like this in `package.json`?

```json
{
  ...
  "hoodie": {
    "env": "production",
    "production": {
     … // production settings
    },
    "development": {
     … // development settings
    }
  }
}
```

…where `hoodie.env` could be overwritten with any `rc` method, to pick the env.

> …or accepting functions as configuration values

This is a useful feature, but I’m unsure where to use it. Do you have any examples for this, aside from the custom account request handlers (or other things that could be in some sort of plugin).

**Comment by gr2m** [comment]
It would be interesting to get insights from the folks at Webpack, Grunt and others, who all ended up having a configuration in the form of a JS file instead of JSON. 

One other reason in favor of JS is that it allows for comments, which JSON does not.

The problem I see with this 

```json
{
  "hoodie": {
    "default_env": "development",
    "production": {
       "foo": "bar"
    },
    "development": {
       "foo": "quux"
    }
  }
}
```

is that for simple apps we wouldn’t need different environments, but we still want to support them eventually. And with JavaScript it scales better for the simplest to the most complex configuration as we can add conditions and event split it up into modules.

**Comment by janl** [comment]
> And with JavaScript it scales better for the simplest to the most complex configuration as we can add conditions and event split it up into modules.

As with our other API design, what use-cases do you have in mind for this?

**Comment by janl** [comment]
> Webpack, Grunt

These are build tools, I'm not at all surprised just JSON doesn't work for them. But they are solving very different problems from Hoodie.

**Comment by gr2m** [comment]
My main motivation was to make Hoodie easire to deploy to Blue mix, but there are other and probably better ways to address it.
