### ISSUE TITLE
Extending _api through plugins

### ISSUE THREAD

**Issue by inator** [hoodiehq/discussion#23]
This relates to a question @janl asked here: https://github.com/hoodiehq/discussion/issues/4#issuecomment-33898332

I think it would be great if the plugins API would allow for the addition of _api routes and handlers.  Jan may have had that in mind, but I thought I'd toss it out for a more explicit discussion.  Is it do-able?

**Comment by gr2m** [comment]
this is now possible: http://docs.hood.ie/en/latest/guides/plugins.html
