### ISSUE TITLE
Check login on server

### ISSUE THREAD

**Issue by varunnaik** [hoodiehq/discussion#26]
I'm building an app where I need to clear data from the server occasionally (part of the business logic).

If a user who was previously using the application attempts to connect back to the server after the server has been wiped, the system is in an inconsistent state, with the user logged in on the user's device but with no corresponding user on the server.

Is there any way to check if the user exists on the server without signing out and signing in again?

**Comment by gr2m** [comment]
@varunnaik hey I know it’s ... ehmm ... been a while, but is this still relevant for you? Lots have happened in Hoodie land since you asked, but your question might still be relevant.

Do you need an API that checks if an account with a given username exists or not?
