### ISSUE TITLE
Discover idle users on the client and server

### ISSUE THREAD

**Issue by janl** [hoodiehq/discussion#28]
Use-case for detecting idle users on the server:

Imagine a chat application that should notify active users if a participant has become idle, or even disconnected from the chat by way of not using the explicit `signOut()` method (e.g. close tab, close browser, put computer to sleep, leave wifi/cell area with the phone etc.)

Use-case for detecting idle users on the client:

Imagine a user opening an app in a browser tab and leaving it idle for longer than the session timeout. How can we detect this reliably in the client to a) inform the user about the situation and b) do the right thing\* for the data storage part.

(\* this might be explicitly keeping and storing for sync any existing data, or explicitly discarding any existing data, because it was only valid in the previous session context)

---

Technical proposal to solve server side detection:
1. (simple, no changes to hoodie-server required, can be done in a plugin): create a plugin that periodically sends a “ping” from the client to the server. The server (hook) can keep track of all clients sending in their ping in an LRU cache and mark those older than X as expired and start actions based on that.
2. (needs a new hook in hoodie-server): add a new hook to hoodie-server that a plugin can hook into that gets sent a user’s information as they make a request. This data can go into an LRU cache, similarly to 1. that then can further be used to decide when a user is idle and start actions from there.

Approach 1. is very simple to do and can be done today, but it creates a secondary channel for session live-ness, which uses extra network requests. By and large this shouldn’t be a big problem, but this can be improved by approach 2. that just piggy-backs on the already existing normal requests. However this is a little more work and requires a new version of hoodie-server. The main LRU cache logic can be re-used in either implementation.

---

Technical proposal to solve client side detection: TBD cc @espy @svnlto @gr2m.

**Comment by gr2m** [comment]
with the new Hoodie, it’s pretty trivial to add a request life cycle extension using a plugin which is a hapi pluing on the server side. 

I’m going to close this due to lack of inactivity. If someone wants to champion it and e.g. create a blog post or guide for documentation about it we can reopen or create a follow up issue
