### ISSUE TITLE
Add “roles” to user accounts

### ISSUE THREAD

**Issue by janl** [hoodiehq/discussion#29]
Imagine an app that has users, admins and app-admins. Users and app-admins we’ve got covered with regular users and pocket, but what about admins that need to be able to do things that regular users are not allowed to, but are also not as powerful as app-admins that have essentially raw access to all CouchDB?

**Comment by gr2m** [comment]
there is now an API to manage roles in accounts: https://github.com/hoodiehq/hoodie-account-server-api#apiaccountrolesadd
