### ISSUE TITLE
tag commit messages

### ISSUE THREAD

**Issue by svnlto** [hoodiehq/discussion#3]
@caolan and myself have started prefixing commit messages like the following:

[npm] for npm related commits (dependency chances, version bump)
[minor] for minor changes
[fix #issueId / PR] for related commits
etc.

what are your thoughts on this?

/cc @espy @gr2m @janl

**Comment by Charlotteis** [comment]
I think we are moving/have moved towards a commit message style like: `fix(accessibility): improve search labelling` for both consistency, and use with @gr2m's semantic-release. So I think I'm good to close this? :)

**Comment by gr2m** [comment]
just fyi, it's @boennemann's semantic-release :)
