### ISSUE TITLE
Add static asset serving to plugins for frontend code

### ISSUE THREAD

**Issue by janl** [hoodiehq/discussion#30]
Image a plugin that not only extends `Hoodie`, but also defines its own user interface bits. Once could load the resources via XHR, and serve them over the web hook API, but that’s clumsy.

For pocket we already allow serving of all sorts of frontend assets from a folder.

We could add `./hoodie.pluginname/` analogous to `./hoodie.pluginname.js` to be the document root for plugin assets and the server that over `/_api/_plugins/pluginname/_assets`, or something of that vein.

**Comment by gr2m** [comment]
Hoodie supports a public folder for plugins which is served at `/hoodie/<plugin-name>`. We don’t yet document it at http://docs.hood.ie/en/latest/guides/plugins.html, but here is an example: https://github.com/hoodiehq/hoodie-plugin-hello-world/tree/master/hoodie/public
