### ISSUE TITLE
Long Polling and iOS Safari

### ISSUE THREAD

**Issue by varunnaik** [hoodiehq/discussion#33]
It seems any XHR image requests made only execute when a running long poll finishes. I use AngularJs to load images like so: <img ng-src="/images/products/{{product.id}}.png"/> which creates a request when I assign a value to product.id sometime during app execution. The request for this image does not seem to  finish till Hoodie's long poll finishes (See screenshot, all images load together after 25s).

![image2](https://cloud.githubusercontent.com/assets/916835/2719256/ebc3bace-c55d-11e3-94c9-d7b154e279e5.jpg)

I then modified hoodie-server/node_modules/hoodie/src/lib/store/remote.js to change the timeout to 11s, which resulted in the screenshot below (all images load together after 11s).
![image3](https://cloud.githubusercontent.com/assets/916835/2719270/1df9b70a-c55e-11e3-97c4-70d93182159a.jpg)

This seems to affect only Safari on iOS (I tested with iOS 7.0.3).

I know that this is not precisely Hoodie related (because it should affect all long poll requests) but any help would be appreciated.

Will update this as I get more information.

**Comment by gr2m** [comment]
We now use PouchDB in the new Hoodie. Could you please check if the problem still exists as reported? You can check with https://github.com/hoodiehq/hoodie-app-tracker.

If it's no longer relevant, please ignore, we will close the issue if there is no more activity

**Comment by peetersn** [comment]
Please close. Thanks!
