### ISSUE TITLE
Even more Ubersicht

### ISSUE THREAD

**Issue by boennemann** [hoodiehq/discussion#36]
Hello team Hoodie (:

I wanted to give you some feedback on my experience with getting started.

First of all the website really is excellent for the bigger scope of the project and doing the first few steps, but once I started digging deeper, or running into problems it turned out that the information is spreaded across too many locations and fragmented.

You already realized that it's hard to stay on top of issues across all the repositories and that's why **Ubersicht** came to life. While it's without question a super awesome tool, it's **focused more on team members**, or people who are already into hoodie.

It's totally reasonable, even necessary, to have that many repositories. I just couldn't find one **central description of which module does what** (I know this might seems obvious, but still), how they matter to me as a user, how I interact with them, where to look for existing issues, create new ones and which readmes to read.

Which leads me right to the next point – **Readmes**. Many of the repositories have their own readme, beginning with a general introduction to hoodie. It doesn't seem like the general intros are synced between the repos or the website which makes it hard to keep them up to date and as a reader I get the impression that I've already read them. That way I might skip over essential information. @janl already started a discussion about versioning in #17 where he states that even though the modules are versioned independently they are associated with a certain hoodie release.

I propose to have **one central Readme** that contains examples, troubleshooting etc. that matter to the user, together with the submodule description I mentioned earlier (This should also be the one that is distributed with `my-first-hoodie`). The specific repos' readmes should only contain information relevant for development and maintenance.

I know you don't want to use version numbers for marketing and that's a good thing imho. Nonetheless **it would benefit developers to communicate releases transparently** (also please employ pre-release flags if something is unstable, untested or super new), so they can troubleshoot better, and ultimately report bugs that are specific to a certain version. Changelogs would be awesome, too. I guess the Angular team already nailed that with their [commit message conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y) and automatic [changelog generation](https://github.com/btford/grunt-conventional-changelog).

As discussed in https://github.com/hoodiehq/hoodie.js/issues/212 and #31 of course the project would benefit from a source generated documentation for both the frontend and server API as well as more in depth and profound deployment instructions.

I hope my feedback is relevant to you and I'd love to help fixing stuff.

Best,
Stephan

**Comment by gr2m** [comment]
We addressed most of these points meanwhile :) I’m gonna close it as part of my issue triaging
