### ISSUE TITLE
Hoodie API - SignUp / SignIn confusion

### ISSUE THREAD

**Issue by kaalita** [hoodiehq/discussion#43]
This is about the names and concepts for the hoodie account.

I noticed, that every time I do something with HOOHoodie it takes me some time to get the difference between signIn and signUp. The methods just look so similar and even the signature is the same. Others on Twitter confirmed that it was hard to distinguish, also UX research confirms that:
http://uxmovement.com/buttons/why-sign-up-and-sign-in-button-labels-confuse-users/

So I'd like to change it for the iOS SDK (even if it's just for my own sanity ;-) also it's still pretty safe to change the API there). 

But I would love to discuss better alternatives here too and get feedback from some others. So far suggestions are:
- CreateAccount & SignIn
- CreateAccount & LogIn
- Register &  LogIn
- Register &  SignIn

Any thoughts / suggestions on that?

**Comment by gr2m** [comment]
more arguments for the discussion:
https://twitter.com/smashingmag/status/555836032886009858

**Comment by gr2m** [comment]
I know it’s been a while :) but adding some thinking out loud, based on my experience with the new Hoodie.

In the old version `hoodie.account.signUp()` did two things:

1. created an account
2. signed you in

In the new Hoodie, we separated these two things, as we want to make custom confirmation workflows a first-class citizen. And with that in mind, `.signUp` makes indeed less sense to me. 

I still like the clear naming convention with all methods starting with `sign*`, I think they are easier to remember, but I tend to agree now that `account.signUp` should be more something like `account.create` based on the new semantics.
