### ISSUE TITLE
Security Hoodie

### ISSUE THREAD

**Issue by carlosbier** [hoodiehq/discussion#45]
Hello peoples,

First sorry, my english is pessimous! I hope that can understand my questions :)

I'm user Rails, but knows Hoodie and I love this :)

My question: Hoodie is very simple, enough to call signUp to register user. In rails, we have a combination key to security a form send data. Server also accept post, (example) that have a key generated random in form. This is ensures that direct call don't work.

In hoodie, if user acess a instance variable via console, he can execute any methods? This does not allow an attack DDOS? Our massive register (a loop of stored objects)?

**Comment by gr2m** [comment]
I think we can close this issue? If not, can we create a follow up issue with an actionable description of what and why we need to implement / document?
