### ISSUE TITLE
hoodie.store: enforce `type` property or not?

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/discussion#67]
Hoodie wants to provide the simplest possible API in order to empower as many people as possible to build data driven apps.

Today's API to store a new Todo object looks like this:

```js
hoodie.store.add('contact', {name: 'John Doe'})
```

The question is, can we simplify it to

```js
hoodie.store.add({name: 'John Doe'})
```

## Motivation

It might look like a subtle change to more experienced developers. But to people new to programming, it significantly cuts the complexity to create simple applications, or first iterations of more complex ones. It perceivable lowers the required learning curve for first results, which might motivate to learn about more complex, but also more powerfull APIs later, when they become necessary.

## Challenge

As soon as an app has more than one object type, say 'contact' and 'company', the type must be stored with each object. To simplify working with different kind of objects, hoodie provides scoped stores

```js
contactStore = hoodie.store('contact')
companyStore = hoodie.store('company')
contactStore.on('change', renderContacts)
companyStore.on('change', renderCompanies)
contactStore.add({name: 'John Doe'}) // {type: 'contact', name: 'John Doe'}
companyStore.add({name: 'Acme Inc'}) // {type: 'company', name: 'Acme Inc'}
```

The challenge is to provide the convenience of scoped stores with preset type properties without confusing the usage of the simple API, even when manually setting the type property.
To achieve this, different events must be triggered when the type of an existing object is changed for `hoodie.store` and `hoodie.store(type)`. Example:

```js
// {id: 'John', type: 'contact'} exists

hoodie.store.on('change', log1)
hoodie.store('contact').on('change', log2)
hoodie.store('person').on('change', log3)

hoodie.store.update('John', {type: 'person')}

// | #    | event name | object                        |
// | log1 | update     | {id: 'John', type: 'person'}  |
// | log2 | remove     | {id: 'John', type: 'contact'} |
// | log3 | add        | {id: 'John', type: 'person'}  |
```

The benefit of this behavior is that people new to Hoodie can use the simple `hoodie.store` API without any restrictions or required knowledge about the `type` property. And for more experienced users, the scoped store APIs behave as expected.

## Implications

The current Hoodie API always enforces a `type` property, and we prefix all object IDs with it. For the example above, the object would have looked like this: `{id: 'contact/John', type: 'contact'}`. We benefit from that ID convention as all IDs are indexed by default in our database, which makes finding all objects of one type very efficient by filtering with the type prefix. The disadvantage is that Hoodie cannot handle objects that do not follow this convention, which makes the integration with existing systems harder.

In order to keep finding objects of one type efficiently we need to add a custom index `by_type` to our (local) database.

## Any thoughts?

I thought a lot about this and think it's worth the extra work. I wonder if I missed something though, so please comment with your questions, concerns and ideas.

**Comment by janl** [comment]
> In order to keep finding objects of one type efficiently we need to add a custom index by_type to our (local) database.

Could we not still rely on `allDocs()` and `type/` prefix? Objects with no type would just not findable that way.

**Comment by janl** [comment]
Overall: I like the thinking behind all this.

**Comment by gr2m** [comment]
> Could we not still rely on allDocs() and type/ prefix? Objects with no type would just not findable that way.

If you use the `type/` prefix for objects that have one, we'll need to delete & create an object each time `.type` gets set or changed.

**Comment by janl** [comment]
Good point. Too bad, I liked this a lot :) It’s not that views for this are any bad, but it is always better to use fewer things. But maybe let’s just roll with the better API and fix any implementation issues, if/when they arise.

**Comment by nicpitsch** [comment]
> The benefit of this behavior is that people new to Hoodie can use the simple hoodie.store API without any restrictions or required knowledge about the type property. And for more experienced users, the scoped store APIs behave as expected.

IMHO the option to ignore the type makes things more confusiung for less experienced users, not easier. I remember when i had first insights into the philosophy behind NoSQL- respectively document-oriented databases. Having experiences with relational databases, it is/was natural to assign documents to some sort of type/collection. In my opinion the type property is kind of self-evident, also for users without database background. Consider a wardrobe: we like to have the socks with the socks, the shirts with the shirts and the pants with the pants and so on (at least theoretically..). Means one of the first thoughts when collecting data is: 'how can i retrieve it later?'.

**Comment by gr2m** [comment]
we decided to make the `type` property optional:
https://github.com/hoodiehq/hoodie-client-store

This will land in next Hoodie
