### ISSUE TITLE
my new plugins not show on http://plugins.hood.ie/

### ISSUE THREAD

**Issue by gabrielmancini** [hoodiehq/discussion#68]
some one knows why?

**Comment by janl** [comment]
which ones?

**Comment by gabrielmancini** [comment]
all of then,

https://github.com/goappes/hoodie-plugin-oauthio
https://github.com/goappes/hoodie-plugin-profile
https://github.com/goappes/hoodie-plugin-pubsub
https://github.com/goappes/hoodie-plugin-socialmedia

**Comment by janl** [comment]
I have no idea why this happens. This is the code that we have running, maybe you can have a look?

https://github.com/hoodiehq/hoodie-plugins-www

**Comment by gabrielmancini** [comment]
local works fine, mabe needs a restart

**Comment by janl** [comment]
it got plenty of restarts. Does it works locally for you when you add a new plugin after you run the plugins.hood.ie code for the first time? E.g. do updates work?

**Comment by gabrielmancini** [comment]
when i run the plugins.hood.ie code for the first time works fine.
it load all plugins

**Comment by janl** [comment]
@gabrielmancini yes, but what happens when you now add a new module to npm? Does it get picked up?

**Comment by gabrielmancini** [comment]
@janl  i will plublish a new plugin in some hours, i will test locally, and put the results here...

**Comment by gabrielmancini** [comment]
not update. 
![scrennshot](http://www.zimagez.com/full/215712f5770f940e817defaa1cf6b7547a22e66f8064571a6924c0fb25bf0a9d62b5cad3478cfb117126a2f6676410fcef19ec70bc3a4bfc.php)

**Comment by Charlotteis** [comment]
I can confirm that these plugins are still not showing up on plugins.hood.ie.

**Comment by janl** [comment]
@Charlotteis we know it’s a bug, but we don’t know where it is :) Wanna have a look?

**Comment by Charlotteis** [comment]
@janl I did try, I can't work it out whether it is us, npm, or the packages themselves. Will find some time this week to delve into it if I can :)

**Comment by janl** [comment]
@Charlotteis I’m pretty sure it is the [`hoodie-plugin-plugins`](http://github.com/alanshaw/hoodie-plugin-plugins) module :)

**Comment by gr2m** [comment]
all plugins that are prefixed with `hoodie-plugin-` can be found via npm search, to which we redirect now: http://plugins.hood.ie/
