### ISSUE TITLE
callback 4 life

### ISSUE THREAD

**Issue by gabrielmancini** [hoodiehq/discussion#70]
Hoodies, 

  There is a way to use Hoodie.JS with callbacks insted promisses ?

Cheers

**Comment by zoepage** [comment]
Why do you need to use callbacks? Is there a specific issue or... use case? :)

**Comment by gabrielmancini** [comment]
with callback i can wrap in jquery promise or angular promise or using async or q i choose the task flow.

**Comment by zoepage** [comment]
Like @gr2m already mentioned on IRC:
"you'd need to make custom wrappers around the hoodie methods if you want callbacks.
 Hoodie does promises as they are more expressive and simpler to get started with, that's not going to change :)"
