### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by gabrielmancini** [hoodiehq/discussion#72]
any one knows this error?

the log :
http://pastebin.com/ef1qStet

**Comment by janl** [comment]
yeah, it comes up when you have more plugins set up, it is harmless for now :)

**Comment by janl** [comment]
filed this for future reference: https://github.com/hoodiehq/hoodie-server/issues/341
