### ISSUE TITLE
offline or user not found

### ISSUE THREAD

**Issue by gabrielmancini** [hoodiehq/discussion#73]
Hi Hoodies,

   How i know if the user exists or no? and how that validation behavior in offline first idea?
   If the users exists before but he is dropped from the base... 

   Other thing, there is a way to know how the clients are online inside a plugin? 

thanks

**Comment by gr2m** [comment]
> How i know if the user exists or no? and how that validation behavior in offline first idea?
If the users exists before but he is dropped from the base... 

Do you mean whether we can differentiate between a user having no account, and a user who’s account has been deleted? This could be possible ... but could you please create a follow up issue if this use case is still relevant, and give more context for it?

> Other thing, there is a way to know how the clients are online inside a plugin? 

I don’t think this would technically be possible right now. Maybe we come up with a way to persist session data so at least you will know when a user was active for the last time, but you cannot tell if a user is online right at this point
