### ISSUE TITLE
What should we use to replace gratipay?

### ISSUE THREAD

**Issue by Charlotteis** [hoodiehq/discussion#74]
Following on from this PR: https://github.com/hoodiehq/hood.ie/pull/175

I noticed the hoodie gratipay account had been deactivated, leaving us without one method of receiving small regular sums of money. I was wondering if we should explore similar options? I know I'd like to offer a small amount to hoodie each month :+1:

**Comment by janl** [comment]
@Charlotteis the short of it is that this is more trouble than it’s worth for tax reasons, because Hoodie financials are managed by an incorporated business in Germany :/

**Comment by Charlotteis** [comment]
Ah, that's a shame :(
