### ISSUE TITLE
The Hoodie Module Structure

### ISSUE THREAD

**Issue by janl** [hoodiehq/discussion#77]
This is a sub-issue of https://github.com/hoodiehq/discussion/issues/76 

(copied original text)

There are a bunch of changes we want to make to all the modules on http://github.com/hoodiehq. The prime objective here is to unify a few things across all repositories in a way that the development experience on each module, be it a CSS library, our website or core JavaScript code, is the same everywhere.

One thing we’d like to encourage and pioneer is the use of `README.md` files in all subdirectories, with information what the particular sub-part of a module is doing and why. That way, our code is much easier to navigate and learn.

In addition, where it makes sense, modules will generate and expose their automatically generated API documentation for pick-up by a central documentation location and for offline viewing.

We’d like to **move away from grunt** as a built tool because it is a bit unwieldy. We’ll be moving to npm scripts for our built scripting needs.

We want to **standardise on a single set of commit message conventions** for all the types of commits we have across all repos. And we want to enforce these with pre-commit hooks that have friendly error messages for newcomers to do the right thing.

This is a bit technical, but we found a neat solution to make this easy for everyone. A pre-commit hook is a piece of software that `git` runs to determine whether it should allow the user to make a commit. We want to use these hooks to ensure that all commit messages follow our standard format of `type(scope): message` with `type` and `scope` being from a strict set that has semantic meaning down the road of the lifecycle of a module.

Pre-commit hooks are something that each user has to install for themselves, they are not part of a `git clone`. In order to avoid everyone having to do this manually, we propose this procedure:

1. all modules have a require new module, say `hoodie-commit-hooks` or `hoodie-developer-tools`.
2. if the require fails, we print a nice message like “please run this command: `npm install -g hoodie-commit-hooks”.
3. Now the require succeeds and it can install the pre-commit hook in the current repository.

Things we want to enforce with pre-commit hooks:
- commit messages
- `package.json` structure and order
- anything else that needs enforcing at that stage.

This should **make the experience of contributing to a single module a lot more pleasant** and **remove a lot of the burden of reviewing and maintaining code** from the existing developers.

**Comment by janl** [comment]
Here is how we are going to do this:

For each repo, we:
- [ ] create a `next` branch
- [ ] update package.json to include module name without `hoodie-` prefix, if applicable

Module Meta
- [ ] install `semantic-release` with `semantic-release-cli`
- [ ] install `semantic-release` plugins (fill in @boennemann)
- [ ] add hoodie-hooks (name TBD) dev dependency
- [ ] add `standard` package

Module Content
- [ ] change `CONTRIBUTING.md` to point to https://github.com/hoodie/hoodie/CONTRIBUTING.MD
- [ ] remove change log
- [ ] remove `.jshintrc`
- [ ] port test startup from grunt to npm scripts
- [ ] remove `Gruntfile.js`

READMEs
- [ ] READMEs don’t include docs
- [ ] fixed README structure (structure TDB, focussing on contributing), minimal “Usage” section where applicable
- [ ] README contributing sections: badges, first contacts (2), chat, usage
- [ ] sub-READMEs in every sub folder explaining briefly what is going on there

Directory structure:
- depends on type of module

**Comment by janl** [comment]
Once we are done with every plugin and the new architecture can go live, we do this:
- [ ] change the `master` branch to `before-x.y.z-master` (where `x.y.z` is the next major version for this module
- [ ] make the `next` branch the new `master` branch
- [ ] rename the module to it’s `package.json` `name`
  - for internal modules, that means removing the `hoodie-` prefix
  - for external modules (like plugins, it means keeping the `hoodie-` prefix

**Comment by gr2m** [comment]
I guess we can close this? If not, can we create a follow up issue of the points which are still relevant today?
