### ISSUE TITLE
commit message convention

### ISSUE THREAD

**Issue by janl** [hoodiehq/discussion#78]
This is a sub-issue of https://github.com/hoodiehq/discussion/issues/77

Regardless of whether we enforce this strictly or lazily, we should agree on on commit message conventions.

Since we are all over the place at this point, this issues is more of an on-the-go collection of suggestions:

For changes to `package.json`, `.gitignore`, `.npmignore` etc:

> chore(meta): description

To be continued…

**Comment by zoepage** [comment]
FYI, especially for the new contributors, this are our guidelines we are working with:
https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines

**Comment by gr2m** [comment]
we added a section to [Hoodie’s CONTRIBUTING.md](https://github.com/hoodiehq/hoodie/blob/master/CONTRIBUTING.md#commit-message-conventions)
