### ISSUE TITLE
Database Permissions

### ISSUE THREAD

**Issue by mtwalsh** [hoodiehq/discussion#79]
Hi,

I'm contemplating Hoodie for a web application project, one area I'm struggling to plan is how Hoodie would allow us to accomplish the permissions structure we need.

The app will handle two types of documents, let's call them “applications" and “reports".

1. Users can create applications and only access their own applications
2. Admins can access and edit all applications
3. Admins can create and edit all reports even those created by other admin users
4. Users cannot access reports

So by default Hoodie gives each user their own database so that covers point 1.

For point 2, we'd need each application to be replicated into another database which only admin users have access to, so working in a similar way to the Hoodie.js Global Share Plugin, albeit not with public access to that database.  And any edits to that database would need to be replicated back to the source/users database. (Or would the admin simply load the record from the source users database when editing rather than the replicated database?)

For point 3 we'd create a new database purely for reports, which all admin users can access.

For point 4 we'd ensure users do not have access permissions to the reports database.

So in terms of a custom plug-in for this it would need to:

Follow a similar approach to the Hoodie.js Global Share Plugin, by creating an "applications" database and replicate applications from user's databases into this database for admin only access.  I'm then assuming admins would make any updates to applications on the document stored in the users database which is then replicated back to the admin only applications database.  So the replication is always one-way.

Then perhaps manually we'd handle the creation of the reports database and creation of admin users with access to it via Futon.

Am I making any sense?

**Comment by gr2m** [comment]
Yeah that all sounds good to me. You could also setup bi-directional replication between the users databases and the central applications database, and give users with an "yourapp-admin" role access to the applications database. The replications would be filtered, so only applications get get replicated from the users database -> applications database, and only applications belonging to the respective user get synced back.

But your idea of making the applications database read-only will work as well. But you'd either need to add the "yourapp-admin" role to the user databases' security, or to expose a custom API endpoint. I think the former would make more sense, as you'd benefit from the whole syncing part.

Hope that helps?

**Comment by mtwalsh** [comment]
Thanks Gregor, yes that's great to hear I'm not a million miles away, thanks for responding.
