### ISSUE TITLE
Unify GitHub Issue Labels

### ISSUE THREAD

**Issue by janl** [hoodiehq/discussion#80]
Our Issues have different sets of labels that are coming from different times in the past. We should reset all that and use the same labels everywhere.

We should be careful to not just delete all labels, but make sure we transition issues that already have labels to the final versions.

We should have at least labels signifying:
- type of issue
- severity of issue // e.g. how much it impacts end-users
- frequency of issue
- is this a beginner issue / beginner only issue?

What else?

**Comment by boennemann** [comment]
The labels we currently specified, **but don't consistently use**, are defined in the [triaging process](https://github.com/hoodiehq/hoodie/blob/master/TRIAGING.md). ([full list](https://github.com/hoodiehq/hoodie-dotfiles/blob/master/labels.json))

They're a good base I guess :)

**Comment by Charlotteis** [comment]
@janl we do have a tool to give all github repos the same labels, which I updated, but @boennemann said it was broken when we tried to update everything

**Comment by gr2m** [comment]
I fixed the script, it now adds new labels and removes others that are not in the config

**Comment by Charlotteis** [comment]
I am happy to close this issue, thank you @gr2m :)
