### ISSUE TITLE
Confusion about publishing/sharing global data

### ISSUE THREAD

**Issue by JanaFlauschata** [hoodiehq/discussion#81]
I started quite excited to adapt my project for using hoodie but now I'm definitely confused.

I understand that hoodie.store() stores all data privately for the current user. This data won't be shared and it is advised to use https://github.com/hoodiehq/hoodie-plugin-global-share.

global-share seems to be sufficiently documented (have not tried using it yet ;)), but it is said that all published data will be editable by ALL users! so this is not really usable for storing user profiles in my app.

There's a reference to https://github.com/hoodiehq/hoodie-plugin-shares whose api suggests that data can be shared read only or with certain users. That seems nice but the project seems to be quite dead...

For the https://github.com/elmarburke/hoodie-plugin-direct-messages plugin there's no real documentation (not sure about whether the plugin creation tutorial reflects the current state). The project has not been updated recently and when I install the plugin my hoodie server won't start up properly...

So what to do?
How can I share read only data and how can I have a given set of users modify the same data?
Can't I do this using hoodie currently? :(

Any clarification is highly appreciated...

**Comment by JanaFlauschata** [comment]
Ok, I fixed  https://github.com/elmarburke/hoodie-plugin-direct-messages by merging it with the the tutorial snippets. This works fine now (after leaving the last stable hoodie version, cause there were problems with the tasks). I'm sure I can adapt this plugin easily for my purposes.

About https://github.com/hoodiehq/hoodie-plugin-global-share: I thought that I could modify it to use a read only database, cause I won't have the szenario which is described to be problematic for https://github.com/hoodiehq/hoodie-plugin-shares. That means if I want to store user profile and a user wants to leave the public store that will only be the when he is deleted and then it's fine to delete the profile in the global store as well. That should make less problems as storing general public data.

Any thoughts on this or advice for best practices?
Or maybe even advice for where in the millions of repos is the best place to ask questions that people will actually look at? ;)

**Comment by gr2m** [comment]
@JanaFlauschata I'm so super sorry, really, that we nobody got back to you. I think I'm probably the best to help you out and I'm very motivated to, I love the fact that you found your way to Hoodie and give it a try against all its current odds :) 

I'll try to help you out next week, pinky promise! I'm in Boston timezone, happy to pair on your problem for 30 minutes or so some time next week?

**Comment by JanaFlauschata** [comment]
No need for excuses :)
I think you already helped me out on Slack (at least your pic looks quite familiar ;)) I guess Slack might be the fastest way to get Hoodie help for me in the future.

Since I figured out the plugin stuff better now everything's fine and I have a plan for migrating my project. I'm stuck with other stuff now but it's not hoodie-related.

But I'd be happy to come back at you in the future if I need more help :)
Thanks for being kind and helpful!

**Comment by gr2m** [comment]
Glad to hear you made progress, good luck with the rest of the project! Can we close this issue then?
