### ISSUE TITLE
Hoodie needs an editorial team! 📝🔎

### ISSUE THREAD

**Issue by janl** [hoodiehq/discussion#84]
🌴🐴👀💖👽🌂🐘🐥🔥💥🗿🎯🎉

Hoodie is a great, diverse, and ambitious Open Source community. **Our goal is to make web development easier for everyone**.

Part of getting there means telling people about what we are doing. We are now at a stage where we would like to **focus on our communication channels**, in order to better connect the community:

- We want to **keep community members up to date** with day-to-day development of the Hoodie projects and invite everyone to **participate in project discussions**. The goal here is to keep everyone in the loop as well as making it easy for newcomers to join and start participating quickly.

- We want to make sure people who don’t follow Hoodie too closely get a chance to check in every once in a while and **see what is going on**.

- We want to establish the Hoodie blog as **a source of inspiration for the larger Open Source community** by covering web development, offline-first, culture and diversity news that make a difference.

To make all of this happen we need an **excellent and motivated editorial team!**

As a member of that team, you will take care of **creating and finding relevant content**, and share it with the community via our blog, Twitter and so on. 

## 💪Together, the team will:
- **Plan and write blog posts** on or around Hoodie, Hoodie releases, side projects, TGIF, community member profiles, conference and meetup recaps, etc.
- **Solicit and curate contributions** to our blog from the larger community.
- **Plan and manage our Twitter account**, announce new content, help funnel support requests to the engineering team.
- Engage the community: **Welcome new people, wish happy birthday,** etc
- **Coordinate with [@qate_oh](https://twitter.com/qate_oh)** on doing PR around The Hoodie Letter and The Offline First Reader newsletter releases.
- **Find more editorial team members** – the more people who work on this, the more buzz we can create and the more fun we’ll have :)
- Add **pictures of animals in clothing** to [our tumblr](http://meetthehoodies.tumblr.com)
- **Whatever else you think is fun!**

Let the web know about the advantages of Hoodie and simple & easy software development.

## 💝Your perks:
- **This is a call for volunteers!** There is no monetary compensation. *We realise that this limits the amount of time people can bring to this. We hope to be able to find funding in the near future, but we cannot promise anything – except for fun & great connections ;-)*
- You will **work with an international community of web enthusiasts** on a high-profile Open Source Project.
- You get to participate in and **learn the dynamics of a popular Open Source project**.
- More often than not, people’s work within the community is being recognised by a large number of people, which can lead to follow-up engagements outside of Hoodie. (Read: this is good to get your name out). *We know this is a cliché in some industries, but we genuinely believe this could be worth it).*
- Your contributions will be seen by **many, many people around the globe**.
- *A set of Hoodie swag that can’t be bought anywhere.*

## 😅Your skills:
- We are looking for **people with strong communication skills** and a known track record of writing in English.
- We are also looking for people who are **eager to learn and don’t shy away from showing initiative** and taking responsibility quickly.
- We are looking for people who know how to communicate and work in diverse groups, across time zones and with limited availabilities.
- **If none of this applies, but you want to learn, apply anyway! :)**
- It helps if you have a basic understanding of GitHub, but this is not a prerequisite.

*We are especially reaching out to underrepresented groups in technology, including, but not limited to, women, people of colour, LGBTQI+ people and people with disabilities.*

We are aiming to **keep individual commitments at about 1 hour per week**. If you want to (and can) spend more time on this, you are very welcome, but if 1 hour is what you have, that’s perfectly fine! If you have 1 hour every other week, that’s also great :)

## 👻How to apply:

Well, that’s it, in Open Source, you don’t apply, you *do*. But how do you get started?

We still have to figure this out, but instead of coming up with some convoluted scheme, we’d rather discuss with you how to get going, and how we can assist you best to join the community and take up this new role.

You can always chat to any of us in our [online chat](http://hood.ie/chat/), or send us an [email](mailto:jan@thehoodiefirm.com), or reply on this issue, if you have a GitHub account.

But to be really productive, [we’ll be holding official Hoodie Office Hours](https://plus.google.com/hangouts/_/thehoodiefirm.com/hoodie-editorial-team) next Saturday, November 21st, 18:00 CET / 12:00 Eastern, 09:00 Pacific with @Charlotteis and @janl.*. If this time doesn’t work for you, please get in [touch](mailto:jan@thehoodiefirm.com).

We will be using this Google Hangout link next Saturday: https://plus.google.com/hangouts/_/thehoodiefirm.com/hoodie-editorial-team

🎈

**Comment by janl** [comment]
@Charlotteis would that time/date work for you?

**Comment by janl** [comment]
Got a +1 from @Charlotteis on Slack, this is live now!

**Comment by markpalfreeman** [comment]
This is a great idea and I'm totally interested!

I'm free (from Seattle) 9am Saturday—look forward to hearing more.

**Comment by renrutnnej** [comment]
I'm in! I <3<3<3 open source and clear communication efforts, yay!

**Comment by schisepo** [comment]
I'd like to  help too ☺ I have no experience working on Open Source project and would welcome the opportunity to get my feet wet.

**Comment by janl** [comment]
<333 all your feedback is very encouraging!

I’ve updated the bottom of the text with the link to the Hangout for Saturday, see you all there! <3

**Comment by gr2m** [comment]
Wooohoooo Hoodie Editorial Team incoming :D Great work with the outreach @Charlotteis & @janl, and thanks for all the great feedback :heart_decoration:

**Comment by Charlotteis** [comment]
Yaaaaaaay @markpalfreeman @renrutnnej & @schisepo. Can't wait to chat.

**Comment by remixz** [comment]
:wave: I'm interested in helping! I'll definitely be joining the hangout.

**Comment by bnb** [comment]
Hey! 

I'm super interested in helping. I'm an active WG member and contributor in the Node.js Evangelism and Website Working Groups. I've done some freelance articles for Modulus, Rollbar, and a couple others. 

I'm also a Communications student at SUNY Poly in New York State. I'm going into my senior year next semester, taking part in the accelerated BA/MA program in my major.

Web development is my passion, but I have more experience writing and editing technical documents. 

I won't be able to make the Noon meeting on Saturday, unfortunately. Would you guys like to Skype/Zoom/Hangouts another time, or hook up via email? I'd like to get a sense of where you guys are with the editorial, branding, and social messaging for the project.

**Comment by natdudley** [comment]
I'm keen to help out too :+1: UX designer/comms strategist here. 

0900 PST is 0600 NZDT though, so will ping you :smile:

**Comment by Charlotteis** [comment]
Hey @bnb and @natdudley, welcome to Hoodie-Land. If you shoot Jan an email that they provided above, then they can inform you of all the goings on. We are building this fairly from scratch, and what we do have will probably go through changes. This right here is kind of the beginning :)

**Comment by janl** [comment]
@natdudley I’m sorry we didn’t account for NZDT on this first round, we’ll keep you posted, though :)

**Comment by nslater** [comment]
heya! tech editorial person here! v interested in doing this for Hoodie :)

**Comment by Charlotteis** [comment]
@nslater Yo Noah! Are you able to join the Hangout on Saturday?

**Comment by nslater** [comment]
@Charlotteis yup! perhaps even in-person with @janl :)

**Comment by Web-Dev-Rich** [comment]
Hey I'm a new developer and really **love** the open source philosophy. I don't know Hoodie but have just read a bit and I'm gonna try it out :) Would love to be involved but don't really have a track record of writing. I can give enthusiasm and willingness to learn and share. If one of the underrepresented tech groups is new devs in their early 50s then I'm your man. Only wish I could make the hangout :(

**Comment by Charlotteis** [comment]
:tada: :+1: :yellow_heart: @Web-Dev-Rich :yellow_heart: :+1: :tada:

**Comment by janl** [comment]
@Web-Dev-Rich you are a perfect match! Don’t worry about the hangout too much for now. We’ll post the results later and let everyone get involved from that point on in their own time :)

I hope that works for everybody. See you all tomorrow, I’m SO EXCITED <3

**Comment by ike** [comment]
:+1:

**Comment by janl** [comment]
Hey everyone, I’ve put up a veeeeeery preliminary agenda up on https://titanpad.com/SekVO8Otov

There are a few things on there that will only be clear after we explain them in the call, but this gives you a chance to look at things beforehand, and if you have any questions, feel free to put them down there, or here in the comments.

Thanks and see (most of) you all tomorrow!

**Comment by janl** [comment]
And a final note, this is just a suggestion, we can make this about whatever you want :) I just wanted to make sure we have something to start with, but it is by no means prescribed! :)

**Comment by schisepo** [comment]
Hi! Requesting to join the hangout

**Comment by schisepo** [comment]
Sorry had to leave the hangout before it was completed. What are the  next steps?

**Comment by nolanlawson** [comment]
I'm happy to do any copyediting. :) Just send me a draft, lemme know if you prefer UK or US English, and I'll do what I can.

**Comment by remixz** [comment]
@schisepo If you haven't already, I'd recommend joining the Slack group (http://hood.ie/chat/index.html), and joining the #editorial channel. :smile: 

There also was an editorial repo set up here: https://github.com/hoodiehq/editorial There are some issues there, where discussions can start about who wants to do what for the different types of posts.

**Comment by janl** [comment]
Hi everyone!

Thanks again for all of you who made it to the hangout! No worries for everyone who couldn’t make it.

As mentioned earlier in the thread, if you can, feel free to join the #editorial channel on the Hoodie Slack: http://hood.ie/chat/index.html

In addition, we (most @Charlotteis) have started to populate the https://github.com/hoodiehq/editorial repository with information. Start at the [README](https://github.com/hoodiehq/editorial/blob/master/README.md), then have [a look at the issues](https://github.com/hoodiehq/editorial/issues/).

Finally, we all decided to start with the “Meet the Hoodies” series, and I’ve written up a high-level issue on how to get started with this: https://github.com/hoodiehq/editorial/issues/9

I’m beyond happy to have you all on board 💖

PS: If anyone is not comfortable with using GitHub, please get in touch in the Slack chat, or email me: jan@thehoodiefirm.com. We’ll guide you along :)

**Comment by janl** [comment]
I'm closing this now in favour of everything that happens on the editorial repo: https://github.com/hoodiehq/editorial

🔒
