### ISSUE TITLE
[next] rename /hoodie/bundle.js route to /hoodie/client.js

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/discussion#89]
We talk about about "Hoodie client" and it will be mentioned a lot in the documentation, also the main repository is `hoodie-client`. So it would be more consistent to have the route where the Hoodie client is served `/hoodie/client.js`. 

Note that `/hoodie/client.js` is not serving `hoodie-client` 1:1. `hoodie-client` returns a Hoodie constructor, `/hoodie/client.js` returns an instance of Hoodie with options passed in.

Any thoughts?

@boennemann @christophwitzko @janl

**Comment by Charlotteis** [comment]
Sounds good to me, it make sense even if it's not a 1:1.

**Comment by HipsterBrown** [comment]
Makes sense to keep it in sync with the current documentation, especially since "bundle" sounds a lot more related to Browserify than Hoodie. 1:1 FTW. :+1:

**Comment by boennemann** [comment]
> We talk about about "Hoodie client" and it will be mentioned a lot in the documentation, also the main repository is hoodie-client. So it would be more consistent to have the route where the Hoodie client is served /hoodie/client.js.

+1

> Note that /hoodie/client.js is not serving hoodie-client 1:1. hoodie-client returns a Hoodie constructor, /hoodie/client.js returns an instance of Hoodie with options passed in.

_Currently_ it **is** the pre-built hoodie-client though.

**Comment by gr2m** [comment]
it’s decided then, let’s do it: https://github.com/hoodiehq/hoodie-server/issues/459
