### ISSUE TITLE
Hoodie as a Hapi plugin

### ISSUE THREAD

**Issue by alisabzevari** [hoodiehq/discussion#91]
It would be good if there was a hoodie Hapi plugin to user hoodie features along with a Hapi application

**Comment by gr2m** [comment]
Could you describe your specific use case, where you would like to be able to use Hoodie as a hapi plugin?

**Comment by alisabzevari** [comment]
My scenario is something like this:
* I have a simple application with login and a form for user to fill some profile data. I will save the filled information in database which as a complex json object.
* Then there is a page that renders user profile data in different templates.

For the first part, hoodie works perfect. But for the second part, I want to use server side rendering and ability to select custom templates to render profile data.
This is why I think it would be good to run hoodie infrastructure beside a Hapi (or express) application.

**Comment by ransomw** [comment]
i get around that scenario for the most part with client-side templates.

another use case for programmatic access to the hoodie data store on the server side is storing data from http apis that expect server-server communication alongside user data.

two routes to such server-side programmatic usage are
* making hoodie interact w/ existing apis (hapi, express, koa, etc.)
* providing a hoodie plugin API

the first could create an expectation that hoodie support any given server-side framework.

the plugin route might be less taxing:  in this scenario,  hoodie provides a plugin system capable of supporting plugins that allow interaction w/ any given server-side framework and plugins handle the "impedance match" between the hoodie internals and framework XYZ@1.2.3.

**Comment by alisabzevari** [comment]
I am a little familiar with express. So I can think of it as express middleware. Hoodie can be used as a standalone server, then can easily be scaled to a bigger application beside an express application. Developer can migrate its hoodie application to an express application without any change.
I can think of this idea to change hoodie infrastructure from a noBackend stack to 'Gradual Backend' stack!

**Comment by gr2m** [comment]
The idea we currently have for server-side rendering is that you can set the `public` option to a Hapi plugin function instead of a string. If it’s hapi plugin, you must define all the routing yourself and have full control over how the page is rendered before HTML is sent to the client

**Comment by gr2m** [comment]
You can use both https://github.com/hoodiehq/hoodie and https://github.com/hoodiehq/hoodie-server as hapi plugins

Does that work for you?
