### ISSUE TITLE
Are restrictions on id in store intentional?

### ISSUE THREAD

**Issue by shoehn** [hoodiehq/discussion#95]
Hi,

I am currently developing a webapp using hoodie and I want to store information on words in a collection. Hoodie does not allow special chars (such as in the czech word stačí) in ids. This would be a legal id field in couchdb. Is that an intentional design decision or unintended?

It would be a lot easier (and I guess also a lot more performant) if I could use the words, that I need to retrieve over and over again as id.

Thanks for the great work in hoodie!

Best regards

Sebastian

**Comment by gr2m** [comment]
Hey Sebastian, we lifted the restriction in the new Hoodie, can you check out on https://tracker.hood.ie, run `hoodie.store.add({id: 'stačí', amount: 123, note: 'special char test'})` in the console. 

I’d recommend to use the new Hoodie, we will release it soon. You can use https://github.com/hoodiehq/hoodie-app-tracker as a starting point. Here are some work in progress docs: https://github.com/hoodiehq/hoodie/tree/refactoring. Ping us in [Hoodie Chat](http://hood.ie/chat/) if you have any further questions
