### ISSUE TITLE
Request for group based permissioning

### ISSUE THREAD

**Issue by RC1245** [hoodiehq/discussion#97]
I wish to create an application which has multiple groups of users:

The groups will be:
1) Read-only (default) users.
2) Content Managers - These people create accounts for the users in group 1.
3) Administrators have full power

Any ideas how one could go ahead and create this?

**Comment by gr2m** [comment]
hey there, sorry for the late response.

Can you explain the nature of your application a bit further? Do Content Managers create the data that the Read-only users can access? Do you need one or multiple administrators?

**Comment by RC1245** [comment]
Yes, the intention is that the content managers would create the data for the read only users, if the permissions could be managed on the similar leve of flexibility to UNIX file permissions that would make things much easier to manage.

**Comment by gr2m** [comment]
Thanks for the input! It’s not top priority right now, but we will get back to you once we start thinking more about roles and shared data. I’m pretty sure that we can cover your use case with Hoodie in future

**Comment by gr2m** [comment]
we now have an API to create databses which allows to grant/revoke access based on roles:
https://github.com/hoodiehq/hoodie-account-server-api
