### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by peteruithoven** [hoodiehq/discussion#99]
Hi folks, I'm totally new to Hoodie and I was looking for release notes / a change log to get my bearing. See in which version (and release channel) for example the new admin pannel is being implemented, where pouchdb is used etc. Is there a change log or are there release notes?

**Comment by peteruithoven** [comment]
On Slack they helped my to the hoodie repo releases: 
https://github.com/hoodiehq/hoodie/releases

**Comment by gr2m** [comment]
Hey Peter, thanks for looking into Hoodie. The core npm module is `hoodie`, and starting [version 20](https://github.com/hoodiehq/hoodie/releases/tag/v20.0.0) it is using PouchDB in the client. You can see all releases and changelogs here: https://github.com/hoodiehq/hoodie/releases.

The Admin Dashboard was added in [Version 22](https://github.com/hoodiehq/hoodie/releases/tag/v22.0.0). The Dashboard’s repository is here: https://github.com/hoodiehq/hoodie-admin
